/*
 * Copyright (C) 2017 shimoda
 *
 * !!do not edit!!
 * this file is automatically generated by gradle and python script.
 */
package com.googlecode.rhinoforandroid;

public class RhinoUrls {
    public static final String URL_BIN =
        "https://github.com/kuri65536/sl4a/releases/download/rhino-6.1.2/";
    public static final String URL_SRC =
        "https://github.com/kuri65536/sl4a/blob/lang-rhino/rhino/";
}
